# matrix of experiments to run

# These are mini runs intended for testing
matrix:
  size: [4]

# Flux Mini Cluster experiment attributes
minicluster:
  name: materials-science
  namespace: flux-operator
  size: [4]

# We provide the image here for flux-cloud to pull, and specific commands
jobs:
  scanid-112541:
    image: ghcr.io/converged-computing/nsdf-materialscience:ubuntu-20.04
    command: python3 /code/preprocess_radiographs.py preprocess /data radiographic_scan_id_112541
    size: 4
    
  # This is just one experiment, you can add another section for another subject id
  scanid-112536:
    image: ghcr.io/converged-computing/nsdf-materialscience:ubuntu-20.04
    command: python3 /code/preprocess_radiographs.py preprocess /data radiographic_scan_id_112536  
    size: 4
