apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster

metadata:
  name: {{ minicluster.name }}
  namespace: {{ minicluster.namespace }}
spec:
  # Number of pods to create for MiniCluster
  size: {{ minicluster.size }}

  # Disable verbose output and run timing
  logging:
    quiet: false

  # Named volumes expected to be in MiniKube VM, OR on kubernetes node 
  # E.g., for a minikube bind you might do:
  # minikube bind <host>:<minikube-vm>.
  # minikube bind /tmp/data-volumes:/tmp/data.
  volumes:
    data:
      path: /tmp/data
      
  containers:
    - image: {{ job.image }}
      command: {{ job.command }}
      
      # This says to mount the volume called "data" to "/data" in the container
      volumes:
        data:
          path: /data
          
      # custom preCommand logic (run at start of script)
      # here we make sure PATH and Pythonpath are added to flux
      preCommand: |
        asFlux="sudo -u flux -E PYTHONPATH=$PYTHONPATH -E PATH=$PATH"
